#!/bin/sh

. /etc/rc.conf

[ -n ${builder_name} ] || exit 1

chown -R swarming /home/swarming/.swarming
setuidgid swarming env HOME=/home/swarming SHELL=/usr/pkg/bin/bash /usr/local/bin/bootstrapswarm -hostname ${builder_name} 2>&1
