#!/bin/sh

# PROVIDE: newfs_scratch
# REQUIRE: root
# BEFORE: mountcritlocal

$_rc_subr_loaded . /etc/rc.subr

name="newfs_scratch"
rcvar=$name
start_cmd="newfs_scratch_start"
stop_cmd=":"


newfs_scratch_start()
{
	if [ x"${scratch_disk}" != "x" ]; then
		if (dumpfs -s ${scratch_dir} | grep 'clean[[:blank:]]0x0[1|2]'); then
			echo "Scratch disk is clean."
		else
			echo "Initializing scratch disk."
			newfs ${scratch_disk}
		fi
		echo "Mounting scratch disk."
		mount ${scratch_disk}
		mount | fgrep ${scratch_dir} || true
	else
		echo "scratch_disk not set" >&2
	fi
}

load_rc_config $name
run_rc_command "$1"
